---
title: "Project 1"
author: "510569026"
subtitle: "Task2: More Practise for Project 2"
date: "University of Sydney | 12/03/2023"
output:
  html_document:
    fig_caption: yes
    number_sections: yes
    self_contained: yes
    theme: flatly
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

<br>

## Initial Data Analysis (IDA)

```{r}
# LOAD DATA
diet = read.csv("Project1Data.csv")
str(diet)
```

<br>

## Does cooking your own meal really help to maintain good health?

```{r message = FALSE}
library(tidyverse)
library(dplyr)
# Write your code for the given plot here
BMI = diet$BMI

BMI_label = cut(BMI, breaks = c(-Inf, 18.5, 25, 30, 35, Inf), labels = c("Underweight", "Normal", "Overweight", "Obese", "Extremely Obese"))

diet$CookMeals <- factor(diet$CookMeals, levels = c("Always", "Usually", "Sometimes", "Rarely", "Never"))

p = ggplot(diet, aes(x = CookMeals))
p +
  geom_bar(aes(fill = BMI_label)) + 
  guides(fill=guide_legend(title = "Health Status (based on BMI)")) +
  labs(x = "Frequency of Cooking at home", y = "Count", title = "Frequency of Cooking at home vs. Health Condition") + 
  scale_fill_manual(BMI_label, values = c("Extremely Obese" = "red", "Obese"="orange", "Overweight"="yellow", "Normal"="green", "Underweight"="blue"))

```
